GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/668d41186d004120f9dc1431

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "User 3",
    "subscribedToChannel": "Channel 3"
}

###

DELETE http://localhost:3000/subscribers/668d41186d004120f9dc1431
